services:
  redis:
    image: redis:7
    container_name: redis-citibike
    ports:
      - "6379:6379"

  server:
    build: ./server
    container_name: mybikes-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379

  client:
    build: ./client
    container_name: mybikes-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:3000

volumes:
  esdata:
