version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis-citibike
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es-citibike
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana-citibike
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  server:
    build: ./server
    container_name: mybikes-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379

  client:
    build: ./client
    container_name: mybikes-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:3000

volumes:
  esdata:
